apiVersion: v1
kind: Pod
metadata:
  name: nginx 
spec:
  containers:
  - image: nginx
    imagePullPolicy: "IfNotPresent"
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
      - mountPath: /var/www
        name: data-cfsplugin 
  volumes:
  - name: data-cfsplugin
    persistentVolumeClaim:
      claimName: pv5
